language: php

php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6

script: "./vendor/bin/tester tests/ -c tests/php-unix.ini"

before_script:
        - composer self-update
        - composer install --dev --prefer-source